name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install XVFB
      run: sudo apt-get install xvfb

    - name: Start XVFB
      run: |
        /usr/bin/Xvfb :99 -screen 0 1280x1024x24 &
        export DISPLAY=:99

    - name: Build Angular application
      run: npm run build --if-present

    - name: Run tests
      run: npm test
